FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:35792ea4ad1db051981f62b313f1be3b46b1f45cadbaa3c288cd0d3056eefb83 AS build

WORKDIR /src

# Copy the solution file
COPY DotnetApiTemplate/*.sln ./

# Copy all projects into the image
COPY DotnetApiTemplate/Domain/ ./Domain/
COPY DotnetApiTemplate/Application/ ./Application/
COPY DotnetApiTemplate/Persistence/ ./Persistence/
COPY DotnetApiTemplate/Infrastructure/ ./Infrastructure/
COPY DotnetApiTemplate/Presentation/ ./Presentation/
COPY DotnetApiTemplate/API/ ./API/

# Restore all dependencies (NuGet packages)
RUN dotnet restore API/API.csproj

# Build the project (release mode)
RUN dotnet publish API/API.csproj -c Release -o /app/publish

# Runtime stage: use a smaller .NET runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0@sha256:6c4df091e4e531bb93bdbfe7e7f0998e7ced344f54426b7e874116a3dc3233ff AS runtime

# Set the working directory
WORKDIR /app

# Copy the published app from the build stage
COPY --from=build /app/publish .

EXPOSE 4040
ENV ASPNETCORE_URLS=http://*:4040

# Start the API
ENTRYPOINT ["dotnet", "API.dll"]
